language: python
python:
    - '3.3'
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7'

before_install:
    - pip install pipenv
install:
    - pipenv install --dev

script:
    - pipenv run flake8
    - pipenv run coverage run ./manage.py test
after_success:
    - pip install coveralls
    - coveralls
