language: python
python:
    - "3.5"
    - "3.6"

before_install:
    - pip install pipenv
install:
    - pipenv install --dev

script:
    - pipenv run flake8 project
    - pipenv run coverage run ./manage.py test

after_success:
    - pip install coveralls
    - coveralls
